
server.port=8081

spring.datasource.url=jdbc:mysql://mysql:3306/expense_db
spring.datasource.username=root
spring.datasource.password=Exp@App26#X
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.application.name=expense-service
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=expense-service:8081


