
server.port=8083

spring.application.name=analytics-service
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=analytics-service:8083
auth.service.url=http://api-gateway:8085